# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\wangwenhai\workspace\RhinoDeviceScanner\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scanButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.scanButton.setObjectName("scanButton")
        self.gridLayout.addWidget(self.scanButton, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.devTypeComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.devTypeComboBox.setObjectName("devTypeComboBox")
        self.devTypeComboBox.addItem("")
        self.devTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.devTypeComboBox, 0, 1, 1, 1)
        self.deviceTableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.deviceTableWidget.setObjectName("deviceTableWidget")
        self.deviceTableWidget.setColumnCount(0)
        self.deviceTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.deviceTableWidget, 1, 0, 1, 3)
        self.logListView = QtWidgets.QListView(self.centralwidget)
        self.logListView.setGeometry(QtCore.QRect(0, 540, 641, 141))
        self.logListView.setObjectName("logListView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "设备扫描器"))
        self.scanButton.setText(_translate("MainWindow", "扫描"))
        self.label.setText(_translate("MainWindow", "设备类型"))
        self.devTypeComboBox.setItemText(0, _translate("MainWindow", "智慧大屏"))
        self.devTypeComboBox.setItemText(1, _translate("MainWindow", "边缘网关"))
